version: '3'

services:
  frontend:
    image: frontend:latest
    ports:
      - "80:80"
  nginx:
    image: nginx:latest
    # ports:
    #   - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
