version: '3'

services:
  backend:
    image: backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=production
    depends_on:
      - mysql
      - redis
      - mongo
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass onlyd111
    ports:
      - "6379:6379"
    volumes:
      - /home/ubuntu/db/redis:/var/lib/redis
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: onlyd111
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/db/mysql:/var/lib/mysql
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: onlyd111
    ports:
      - "27017:27017"
    volumes:
      - /home/ubuntu/db/mongo:/var/lib/mongo